name: Deploy Application

on:
  push:
    branches:
      - '**'  # This will match any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/heads/fix/') && !startsWith(github.ref, 'refs/heads/feature/')"
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
          cd infrastructure/terraform
          terraform init

      - name: Select/Create Terraform Workspace
        run: |
          cd infrastructure/terraform
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME

      - name: Terraform Apply
        run: |
          cd infrastructure/terraform
          terraform apply -auto-approve

  smoke-test:
    needs: deploy
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/heads/fix/') && !startsWith(github.ref, 'refs/heads/feature/')"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd tests/selenium
          npm ci

      - name: Run Selenium tests
        run: |
          cd tests/selenium
          npm test
        env:
          APP_URL: ${{ steps.terraform-output.outputs.frontend_url }}
